# Generated by Django 5.0.1 on 2024-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updateat',
            new_name='updatedat',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
