# Generated by Django 5.0.1 on 2024-02-03 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_updateat_category_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatedat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
